###########################################################################################
#                                                                                         #
#                             ProDriveBackup                                              #
#                                   By: ProFewGames                                       #
#                                                                                         #
###########################################################################################

# Backup.directory - This value indicates where the backups will be stored after a new one is created.
# Backup.interval - This is the time in ticks that the plugin will automatically create backups, Set as -1 to disable
backup:
  directory: backup
  interval: 1728000 # 1 Day

# When a new backup is created it will be labeled with this. For more DateFormat information
# Visit https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
date-format: d-M-yyyy--HH-mm

# Will the plugin be talkative? Will it send messages whenever something happens.
verbose: true

# Connection Settings
upload:
  host: https://webdav.com/upload
  username: WebDavUser
  password: walrus