name: ProDriveBackup
version: 2.0
description: Uploads backups to Google Drive
main: ratismal.drivebackup.DriveBackup
author: Ratismal, ProFewGames
api-version: 1.15
commands:
  driveBackup:
    description: See all DriveBackup commands
    usage: /drivebackup