main: xyz.ufactions.prodrivebackup.ProDriveBackup
name: ProDriveBackup
version: 3.0
author: ProFewGames
description: Allows you to backup to your server to ProDrive
website: https://prodrive.green-bull.in/
commands:
  prodrivebackup:
    description: Administration backup command
    aliases: [drivebackup, pdb, backup]